---
- name: Install ntp in ubuntu
  action: apt pkg='ntp' state=installed
  when: ansible_pkg_mgr == "apt"

- name: Install ntp in ami
  yum:
    name: ntp
    state: present
  when: ansible_pkg_mgr == "yum"

- name: Start ntp service
  service: name:ntp start=started enabled=yes
