---
- name: Install Jenkins Dependencies
  package:
    name:
      - curl
      - libselinux-python
      - initscripts
      - java
    state: present
  tags:
    - install-dep

- name: Install Jenkins repo
  get_url:
    url: "https://pkg.jenkins.io/redhat/jenkins.repo"
    dest: /etc/yum.repos.d/jenkins.repo

- name: Add Jenkins repo GPG Key
  rpm_key:
    state: present
    key: "https://pkg.jenkins.io/redhat/jenkins.io.key"

- name: Download jenkins
  yum:
    name: jenkins
    state: present

- name: start jenkins
  service:
    name: jenkins
    state: started
    enabled: yes
  tags:
    - start-jenkins
